### ISSUE TITLE
Unable to click the Connect Wallet button 

### ISSUE THREAD

**Issue by charlessundayfr** [adrianhajdin/project_web3_uniswap#3]
Hi,  I'm unable to click the Connect Wallet button after refreshing the page, at 1:36:20 in the video tutorial. There seems to be something blocking the cursor from changing to pointer, and blocking the button from being clicked. Anyone else run into this issue?

PS: _Interestingly enough, when I refresh the page and very quickly place my mouse over the Connect Wallet button, I am briefly able to click the button and open the Metamask Pop-up as usual. But, when the page is fully refreshed, the cursor goes back to the default arrow pointer, and I am unable to click the button._

Your help would be greatly appreciated

**Comment by aatif00002** [comment]
yess i am facing the exact same problem

**Comment by aatif00002** [comment]
please help me out

**Comment by aatif00002** [comment]
@adrianhajdin  please consider it ....

**Comment by charlessundayfr** [comment]
Guys, I found a short-term solution to this by just adding the following to the index.css file in the react-app folder:

```
iframe {
  pointer-events: none;
}
```

There may be a better solution to this that involves updating react-scripts, adding resolutions or overrides (again) to the package.json file,  and maybe even installing npm again — but I didn't have much success doing that without having to start the project all over again. So, hope this helps. Good luck!

**Comment by charlessundayfr** [comment]
For reference, here is a link to the very same problem with more suggested solutions you can try:

https://github.com/facebook/create-react-app/issues/11880#issuecomment-1005409614

**Comment by aatif00002** [comment]
> iframe {
  pointer-events: none;
}

thanks Charles it did work , but why u said it short term solution , will it stop working after a certain period ....
by the way again thank you so much for the help ...  
@W3Charles

**Comment by charlessundayfr** [comment]
No. Perhaps, I used the wrong word. It shouldn't stop working after a certain period, but it may not be considered "best practice". It basically disables all iframes. So, if you have another iframe that you want to work with within the app, you might have to find another workaround for that particular iframe again, that's all. But that shouldn't be a problem when creating this app. Hope that helps. Good luck
